### ISSUE TITLE
Add a filter system for file content

### ISSUE THREAD

**Issue by prisis** [narrowspark/template-sync-action#15]
**Is your feature request related to a problem? Please describe.**
Add the possibility to filter file content, that should be skipped on template sync

**Describe the solution you'd like**
possible syntax for action

```yml
filters:
 - filename:
    - key inside a json file
	- regex
```

**Describe alternatives you've considered**
n/a

**Teachability, Documentation, Adoption, Migration Strategy**
n/a
